services:
  - docker

env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "hQVOwnuPvHYdoHlMGD11XBwqAUCmsk6T29A0FcchaambqVXmiBONVN9a3LUrkxixNAYndnm2VchSbCEOcTtcqcAje+w3owh7mAdBsXUZA03UgnELI4Lw0GAlFQZZSPZYdDU9WVtk6knUMwpBukDuhdL4m2D8LwZIVb+QdP+/mki0TOL0v0XKBATCbSpjmlfpOxVej51JE7QjkzY05Aqig17xnL7DrwEloqAFMPTXhD64kHrdZGyI1p/NtwnCUyoUIupK9MPXlCsxhyORjdvM/2etiv/zyn7I0Yecyv1AUZ7ANDC93np3ck4CzonAc95PbqAmKxs9VVE1WPm+T/gUjXSiufMan3WPIrPMB81QTC2wW+CbX13A+DzsnQrv1PwDQatfcUz0ucb/d1mpKn/i+m96Mgt9YtUF+e9pyA7fAZJQCR5ETM83cNUiLb0hnMriBGN1Rqsk4JkuoT4JI1HOMPc9/vGJEfnOu3cdWgmvnJwIw+7MuBlgUCIZW5vkHoA1ut+LpdaMMiHOA77swWiTXbGIQmhZUArv85WQwTqbdsLtrb+551Za4w5GTz68v6vZ8Ezx06g5HlRMDFWgEZuWvOk/JzQnFhiMbuj1sz+mGjB8KD1hcEucDV4cptfzEWclp1zqQHzdDpvGxg5R6u9/Q8l/uBdLfX0HDQgo13RAsOM="
    - secure: "WInaGLzEdAIhiXHeT65/7mrmVQpIadebp0s0RNTVbeEv31ZQg3qon1FJeRpntb77TQgtZeMGIzT5OhJ528bRTrzgbwIq3VeNRidSVPGle9WPKdH26ElggXiq/gQBhGWtcrrQ4gGXzoTRGN5bg9Mp0+M+YBHlpTe0ilZz3cHEZYnRLVlbmc8gfNqY6QktTeyu9eVVfQ8w9laZgWGuMb4AHJe5sIYXod6XLQhQmSRVFdaoXsErka5jVpDj1e5ReeedBf3nt56OFyltucUuDPMGB13BcrYs0gF90QNAvbkAc4CA4QfliyxEP2fY8bE418XKcL9Yk/0VFEQBSy3YiX2Mv6H83Q7UYZfhtPFwzCPlP0N37PAoxA0zOO/U4pAeMlku6adtRF/1lXGq7qzx4ESMAQEtaMqti54+9zu7h+716ouaE9oWqApZbbjpBg7xl0tJDm5teSnAvYT2NZC0/DmxHfMr72r2PKdfZgcwONUpM6Jb219P+ZPQnHFI3Cu/yb02YkzoYzyAO3hGZCczdY2N9FOMwPS08TckQUBqm4AOl77thWn3kcglt/sT7ltTLr6QF8F3h5OI6p/YNDFCjIqQ0CnZ1LW4IYC62a8T1MRcdNzfUEge4Ch3zGrG4jt+3Fv+9Kr6uwMbKITnS792is+o+Ggva//Vw1BOn0VGAkHjpYY="

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker --version
  - docker-compose version
  - echo "Login into Docker Hub"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - export GIT_SHA=`git rev-parse --short HEAD`
  - echo "Building commit $GIT_SHA"

jobs:
  include:
    - stage: tests
      name: "Unit Tests"
      script:
      - cd Chapter04
      - docker-compose build db
      - docker-compose build test-postgresql
      - docker-compose run test-postgresql
    - stage: tests
      name: "Static Analysis"
      script:
      - cd Chapter04
      - docker-compose build static-analysis
      - docker-compose run static-analysis
    - stage: push
      script:
      - cd Chapter04
      - docker-compose build server
      - docker tag thoughts_server:latest zoneznoober/thoughts-backend:$GIT_SHA
      - docker push jaimebuelta/thoughts-backend:$GIT_SHA
      - docker tag thoughts_server:latest zoneznoober/thoughts-backend:$TRAVIS_BRANCH
      deploy:
      - provider: script
        script: docker push zoneznoober/thoughts-backend:$TRAVIS_BRANCH
        on:
          branch: master        
      - provider: script
        script: docker push zoneznoober/thoughts-backend:$TRAVIS_TAG
        on:
          tags: True
